services:
  - type: web
    name: aura-rag-app
    env: python
    region: ohio
    plan: free
    buildCommand: "bash render_build.sh"
    startCommand: "python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20.12.2
      - key: PINECONE_INDEX_NAME
        value: mini-rag-index
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
